# Generated by Django 3.0.9 on 2020-08-03 20:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('fp_ticket_number', models.IntegerField()),
                ('fp_ticket_title', models.CharField(max_length=400)),
                ('fp_ticket_description', ckeditor.fields.RichTextField()),
                ('fp_ticket_thread_id', models.CharField(max_length=400)),
                ('fo_tickets_topic', models.CharField(choices=[(None, None), ('Slurm', 'Slurm')], default=None, max_length=15)),
                ('fp_tickets_autoresponse', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
